language: java

## export GPG details
before_install:
    - echo $GPG_SECRET_KEYS | base64 --decode | $GPG_EXECUTABLE --import
    - echo $GPG_OWNERTRUST | base64 --decode | $GPG_EXECUTABLE --import-ownertrust

install:
    mvn --settings .maven.xml install -Dgpg.skip -Dmaven.javadoc.skip=true -B -V
addons:
  sonarcloud:
    organization: "robert2411-github" # the key of the org you chose at step #3

## Build and release to maven central
script:
    - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
    - if [ $TRAVIS_BRANCH == 'master' ];
      then mvn clean deploy -DskipTests=true --settings .maven.xml -B -U -Prelease;
      fi

before_deploy:
  - mvn help:evaluate -N -Dexpression=project.version|grep -v '\['
  - export project_version=$(mvn help:evaluate -N -Dexpression=project.version|grep -v '\[')
deploy:
  provider: releases
  api_key:
    secure: SVE019T/2N2KkivxF232+Me2SVEJACKfr5l59ficAU/o8VjOwhRURFsIuDh11G4qgslEUwhZ/6iV/S6b7Mxp9lUcawjJP9lmYsJCrpmOkTZewEISfoFX9TiiExNOLjiBz6yGajhon//0fJOQ6jGsgOj+lzwBG0ov0vVmH9humXMjHcu+I4OLiSvlmb+E5DeQLE5OySr1P2oZfXMrtxLZ6r2G2jmHQJdc8A/aRMZ4T4dkog8jyv3pPuGXBKcRg2EIYjKn/j4W6ads6/sMm0NeHi6Wur3egMEassEK2mvlE/pIaquIjd2IgCEKSg+/KKSmG/lMTnETmREguaCq/+GC/qm9y7rGKN6/sNconAezYIT/KsStQlTfSL7iOmRhZ4DhscN0YYI4CWlE4zTN5KwmOHt2/6aVjFD8hoR4LniIhHNDV9hPwfJ7bmSLMO6Ls5GtY7ll3hAhiFuoIn8ik9JmhOjOebk19IWF/S9u2swaNE35i4546ptF8ytrgCVKmB0wKGI6n4diqrwa+SGJ6kPhGIJ72/+1gzAI9R37lnvOELwt4pgu4LBKod63BOV+ZPyd9IojrAMMl/FX7ssI6LOVAjdQGsj9VOPaprxrA3qYWmmd8EBVkIhgArmxyqhMVjV0IiW4FusRsZE9CEUQgqLi+eA8XQS7UKMCCM8sQnw07YI=
  file:
    - target/spring-boot-starter-springfox-$project_version.jar
  skip_cleanup: true
  on:
    branch: master
    repo: robert2411/spring-boot-starter-springfox
  name: $project_version

#after_success:
#    - bash <(curl -s https://codecov.io/bash)

cache:
  directories:
    - "$HOME/.m2"
